services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/socialapp
      PORT: 3001

  frontend:
    build: ./client
    ports:
      - "3005:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3001

volumes:
  mongo-data: